---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs

params:
  NSX_API_MANAGERS:
  NSX_API_USER:
  NSX_API_PASSWORD:
  NSX_API_CA_CERT:
  NCP_FOUNDATION_NAME:
  NCP_OVERLAY_TZ:
  NCP_TIER0_ROUTER:
  NCP_CONTAINER_BLOCK_NAME:
  NCP_SUBNET_PREFIX:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:
  OPS_MGR_USR:
  OPS_MGR_PWD:

inputs:
  - name: pcf-pipelines

run:
  path: pcf-pipelines/tasks/config-ert/task.sh
